name: 'CI - Releases'
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish Release
    steps:
    - uses: actions/checkout@v3
    - run: chmod +x ./gradlew
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2.9.0
      if: github.ref_type == 'tag'
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MVN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MVN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPGKEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.PGP_KEYID }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSKEY }}
      with:
        arguments: publish -Pversion=${{ github.ref_name }}

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - publish
    if: ${{ always() }}
    steps:
      - name: Notify
        uses: ROMVoid95/discord-webhook@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
